version: '3'
services:

  # TODO: Add "front-server" service
  
  # TODO: Add "back-server" service

  back-server:
    build: ./server
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
    networks:
      - backend
      - frontend
    depends_on:
      - database
    command: /bin/sh -c "sleep 10 && npm start"

  # worker:
  #   build: ./worker
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - PORT=5000
  #     - CLIENT_ID=${CLIENT_ID}
  #     - CLIENT_SECRET=${CLIENT_SECRET}
  #     - CALLBACK_URI=${CALLBACK_URI}
  #     - NODE_ENV=dev
  #     - DB_URI=postgres://unicorn:chocolate@database:5432/rainbow
  #   networks:
  #     - backend
  #   depends_on:
  #     - database
  #   command: /bin/sh -c "sleep 10 && npm start"  # wait until database is ready for conns
  #   # if you ever get permission denied error, look here:
  #   # https://github.community/t5/GitHub-Actions/Permission-Denied-quot-exec-entrypoint-sh-quot/td-p/31249

  database:
    image: postgres:9.6.17-alpine
    restart: always
    environment:
      - POSTGRES_USER=unicorn
      - POSTGRES_PASSWORD=chocolate
      - POSTGRES_DB=rainbow
    volumes:
      - ./db:/docker-entrypoint-initdb.d # tables and stuff
      - db-data:/var/lib/postgresql/data # persist data
    ports:
      - 5432
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
